---
- name: Install dependencies
  apt:
    name: "{{ nodejs_dependencies }}"
    state: present
    update_cache: true

- name: Add NodeSource signing key
  apt_key:
    state: present
    url: "{{ nodejs_signing_key }}"

- name: Manage NodeSource APT repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop: "{{ nodejs_repositories }}"

- name: Ensure NodeJS package is installed
  apt:
    name: nodejs
    state: "{{ nodejs_package_state }}"
    update_cache: true

- name: Ensure global npm packages are installed
  npm:
    global: true
    name: "{{ item.name }}"
    version: "{{ item.version | default('latest') }}"
  loop: "{{ nodejs_global_npm_packages }}"
  loop_control:
    label: "{{ item.name }}"
