---
- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ nodejs_dependencies }}"
    state: present
    update_cache: true

- name: Configure NodeSource APT repository
  ansible.builtin.deb822_repository:
    components: main
    name: nodejs
    signed_by: "{{ nodejs_apt_signed_by }}"
    suites: nodistro
    uris: "{{ nodejs_apt_uris }}"

- name: Ensure NodeJS package is installed
  ansible.builtin.apt:
    name: nodejs
    state: "{{ nodejs_package_state }}"
    update_cache: true

- name: Ensure global npm packages are installed
  community.general.npm:
    global: true
    name: "{{ item.name }}"
    version: "{{ item.version | d(omit) }}"
  loop: "{{ nodejs_global_npm_packages }}"
  loop_control:
    label: "{{ item.name }}"
