---
- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ nodejs_dependencies }}"
    state: present
    update_cache: true

- name: Add NodeSource signing key
  ansible.builtin.apt_key:
    state: present
    url: "{{ nodejs_signing_key }}"

- name: Manage NodeSource APT repositories
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
  loop: "{{ nodejs_repositories }}"

- name: Ensure NodeJS package is installed
  ansible.builtin.apt:
    name: nodejs
    state: "{{ nodejs_package_state }}"
    update_cache: true

- name: Ensure global npm packages are installed
  community.general.npm:
    global: true
    name: "{{ item.name }}"
    version: "{{ item.version | d(omit) }}"
  loop: "{{ nodejs_global_npm_packages }}"
  loop_control:
    label: "{{ item.name }}"
